server:
  port: 8080
  servlet:
    context-path: /swp391

spring:
  datasource:

    url: jdbc:mysql://localhost:3306/EventFLowerExchange
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect  # or MySQL8Dialect if using MySQL 8.x

    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds

payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "65ECNUA0"
    secretKey: "TLBTCNB3L17LF5LQLIZ8XT876R62EPC2"
    returnUrl: "http://localhost:8080/swp391"
    version: "2.1.0"
    command: "pay"
    orderType: "other"
